version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gosec
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused

settings:
  gosec:
    excludes:
      - G101
      - G115
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-dirs:
    - tests
    - vendor
