version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gosec
    - govet
    - staticcheck
    - ineffassign
    - unused
  exclusions:
    paths:
      - tests
      - vendor
      - third_party
