openapi: 3.0.3
info:
  title: MailRaven REST API
  description: |
    Mobile-first REST API for MailRaven email server. Optimized for bandwidth-constrained mobile clients with pagination, compression, and delta sync support.
    
    **Authentication**: All endpoints (except `/auth/login`) require JWT token in `Authorization: Bearer <token>` header.
    
    **Pagination**: List endpoints support `limit` (default: 20, max: 1000) and `offset` parameters.
    
    **Compression**: Responses >1KB use gzip when client sends `Accept-Encoding: gzip`.
  version: 1.0.0
  contact:
    name: MailRaven Team
    email: dev@mailraven.example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://mail.example.com/api/v1
    description: Production server
  - url: http://localhost:8443/api/v1
    description: Local development server

tags:
  - name: Authentication
    description: User authentication and token management
  - name: Messages
    description: Email message retrieval and management
  - name: Search
    description: Full-text search of messages

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Authenticate user and obtain JWT token
      description: |
        Validates email/password credentials and returns a JWT token valid for 7 days.
        Token must be included in `Authorization` header for all subsequent API calls.
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                  description: User's email address
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: SecurePassword123!
                  description: User's password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    description: JWT token (valid for 7 days)
                  email:
                    type: string
                    format: email
                    example: user@example.com
                  expires_at:
                    type: string
                    format: date-time
                    example: '2026-01-29T10:00:00Z'
                    description: Token expiration timestamp (ISO 8601)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimited'

  /messages:
    get:
      tags:
        - Messages
      summary: List messages for authenticated user
      description: |
        Retrieves paginated list of messages for the authenticated user.
        Messages ordered by `received_at` DESC (newest first).
        Returns metadata only (no message body content).
      operationId: listMessages
      security:
        - BearerAuth: []
      parameters:
        - name: limit
          in: query
          description: Number of messages to return (max 1000)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 20
        - name: offset
          in: query
          description: Number of messages to skip (for pagination)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: unread_only
          in: query
          description: Filter to unread messages only
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Message list retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/MessageSummary'
                  total:
                    type: integer
                    example: 142
                    description: Total message count for user
                  limit:
                    type: integer
                    example: 20
                  offset:
                    type: integer
                    example: 0
                  has_more:
                    type: boolean
                    example: true
                    description: True if more messages available
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimited'

  /messages/since:
    get:
      tags:
        - Messages
      summary: Get messages since timestamp (delta sync)
      description: |
        Retrieves messages received after a specific timestamp.
        Optimized for mobile app incremental sync (avoid re-downloading full mailbox).
      operationId: getMessagesSince
      security:
        - BearerAuth: []
      parameters:
        - name: since
          in: query
          description: ISO 8601 timestamp - return messages received after this time
          required: true
          schema:
            type: string
            format: date-time
            example: '2026-01-22T10:00:00Z'
        - name: limit
          in: query
          description: Maximum number of messages to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
      responses:
        '200':
          description: Delta messages retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/MessageSummary'
                  count:
                    type: integer
                    example: 5
                  since:
                    type: string
                    format: date-time
                    example: '2026-01-22T10:00:00Z'
        '400':
          description: Invalid timestamp format
        '401':
          $ref: '#/components/responses/Unauthorized'

  /messages/{id}:
    get:
      tags:
        - Messages
      summary: Get full message content
      description: |
        Retrieves complete message including headers and body.
        Body content is decompressed and returned as full MIME message.
      operationId: getMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Message ID (UUID)
          required: true
          schema:
            type: string
            format: uuid
            example: 550e8400-e29b-41d4-a716-446655440000
      responses:
        '200':
          description: Message retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageFull'
        '404':
          description: Message not found
        '401':
          $ref: '#/components/responses/Unauthorized'

    patch:
      tags:
        - Messages
      summary: Update message metadata
      description: |
        Updates message metadata (currently only `read_state`).
        Idempotent operation - can be called multiple times safely.
      operationId: updateMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: Message ID (UUID)
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                read_state:
                  type: boolean
                  example: true
                  description: Mark message as read (true) or unread (false)
      responses:
        '200':
          description: Message updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageSummary'
        '404':
          description: Message not found
        '401':
          $ref: '#/components/responses/Unauthorized'

  /messages/search:
    get:
      tags:
        - Search
      summary: Full-text search of messages
      description: |
        Searches message sender, subject, and body using full-text index.
        Results ranked by relevance (BM25 algorithm).
        
        **Query Syntax**:
        - Plain text: `invoice` - matches any field containing "invoice"
        - Prefix search: `invo*` - matches "invoice", "invoicing", etc.
        - Sender filter: `from:billing@example.com` - messages from specific sender
        - Phrase search: `"urgent invoice"` - exact phrase match
      operationId: searchMessages
      security:
        - BearerAuth: []
      parameters:
        - name: q
          in: query
          description: Search query (FTS5 syntax)
          required: true
          schema:
            type: string
            maxLength: 1000
            example: invoice
        - name: limit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 20
        - name: offset
          in: query
          description: Number of results to skip (pagination)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Search completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResult'
                  query:
                    type: string
                    example: invoice
                  count:
                    type: integer
                    example: 15
                    description: Number of results in this page
                  total_matches:
                    type: integer
                    example: 47
                    description: Total matching messages
        '400':
          description: Invalid search query syntax
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from `/auth/login`

  schemas:
    MessageSummary:
      type: object
      description: Message metadata (list view)
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        sender:
          type: string
          format: email
          example: billing@sender.example.com
        recipient:
          type: string
          format: email
          example: user@example.com
        subject:
          type: string
          example: Invoice #12345 for January 2026
        snippet:
          type: string
          maxLength: 200
          example: Thank you for your business. Your invoice for January is attached...
          description: First 200 characters of message body
        read_state:
          type: boolean
          example: false
        received_at:
          type: string
          format: date-time
          example: '2026-01-22T10:30:00Z'
        spf_result:
          type: string
          enum: [pass, fail, softfail, neutral, none]
          example: pass
        dkim_result:
          type: string
          enum: [pass, fail, none]
          example: pass
        dmarc_result:
          type: string
          enum: [pass, fail, none]
          example: pass

    MessageFull:
      allOf:
        - $ref: '#/components/schemas/MessageSummary'
        - type: object
          properties:
            message_id:
              type: string
              example: <abc123@sender.example.com>
              description: Email Message-ID header
            body:
              type: string
              example: "MIME-Version: 1.0\r\nFrom: billing@sender.example.com\r\n..."
              description: Full raw MIME message content
            body_size:
              type: integer
              example: 15234
              description: Original message size in bytes

    SearchResult:
      allOf:
        - $ref: '#/components/schemas/MessageSummary'
        - type: object
          properties:
            relevance:
              type: number
              format: float
              example: 0.85
              description: BM25 relevance score (0-1, higher = more relevant)

  responses:
    Unauthorized:
      description: Missing or invalid JWT token
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized
              message:
                type: string
                example: Invalid or expired JWT token

    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Rate limit exceeded
              message:
                type: string
                example: Maximum 100 requests per minute exceeded
              retry_after:
                type: integer
                example: 45
                description: Seconds until rate limit resets
