apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mailraven

resources:
  - ../base/backend-deployment.yaml

patches:
  - target:
      kind: Deployment
      name: mailraven-backend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: mailraven-server:local
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: replace
        path: /spec/replicas
        value: 1
