apiVersion: v1
kind: Secret
metadata:
  name: mailraven-secrets
  namespace: mailraven
type: Opaque
stringData:
  postgres.password: "CHANGE_ME"
  jwt.secret: "CHANGE_ME_TO_32_CHAR_RANDOM"
  minio.access_key: "minioadmin"
  minio.secret_key: "minioadmin"
  redis.password: ""
