package domain

import "time"

// SMTPSession represents temporary state for an active SMTP connection
// (Not persisted, exists only during connection lifetime)
type SMTPSession struct {
	SessionID   string    // Unique session identifier (for logging)
	RemoteIP    string    // Client IP address
	HeloName    string    // Client HELO/EHLO name
	Sender      string    // MAIL FROM value
	Recipients  []string  // RCPT TO addresses
	ConnectedAt time.Time // Connection start time
	BytesRecv   int64     // Bytes received in DATA command
}

// DNSRecord represents a DNS configuration record for the mail domain
// Generated by quickstart command
type DNSRecord struct {
	Type     string // "MX", "TXT" (for SPF/DKIM/DMARC)
	Name     string // DNS record name (e.g., "@", "_dmarc", "mail._domainkey")
	Value    string // DNS record value
	TTL      int    // Time to live in seconds
	Priority int    // MX record priority (10 for primary)
}
